apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${APP_NAME}:latest
          imagePullPolicy: Never # Usa la imagen local construida por Jenkins
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  labels:
    app: ${APP_NAME}
spec:
  selector:
    app: ${APP_NAME}
  type: NodePort # Para poder acceder fácilmente desde localhost
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
